---
title: "ae_waiting_time"
output: html_notebook
---

```{r}

library(tidyverse)
library(janitor)
library(lubridate)
library(stringr)

```

```{r}

ae_waiting_time <- read_csv(here::here("data/ae_activity_waiting_times_apr2022-data.csv")) %>% 
  clean_names()

ae_waiting_time_prior <- read_csv(here::here("data/monthly_ae_waitingtimes_A&E attendances and performance data_202201.csv")) %>% 
  clean_names()

```


```{r}

ae_waiting_time_prior <- ae_waiting_time_prior %>% 
  mutate(year = str_c(
    str_sub(month, start = 1, end = 4)), .before = 1) %>% 
  mutate(month = str_c(
    str_sub(month, start = 5, end = 6)
  ))


ae_waiting_time_prior <- ae_waiting_time_prior %>% 
  filter(year >= 2016)

colnames(ae_waiting_time_prior)

ae_waiting_time_subset <- ae_waiting_time_prior %>% 
  select("year", "month" , "treatment_location" , "department_type", "number_of_attendances_aggregate",  "number_meeting_target_aggregate","attendance_greater8hrs", "attendance_greater12hrs", "discharge_destination_admission_to_same" , "discharge_destination_other_specialty" ,"discharge_destination_residence", "discharge_destination_transfer" ,"discharge_destination_unknown")

ae_waiting_time_subset <- ae_waiting_time_subset %>% 
  filter( year != "2016" | month != "01") %>%
  filter( year != "2016" | month != "02") %>%
  filter( year != "2016" | month != "03") %>%
  filter( year != "2016" | month != "04") %>%
  filter( year != "2016" | month != "05") %>%
  filter( year != "2016" | month != "06")

ae_waiting_time_subset <- ae_waiting_time_subset %>% 
  mutate(year_quarter = case_when(
    str_detect(month, "01|02|03") ~ "Q1",
    str_detect(month, "04|05|06") ~ "Q2",
    str_detect(month, "07|08|09") ~ "Q3",
    str_detect(month, "10|11|12") ~ "Q4"
  ), .after = 1)
           
ae_waiting_time_subset <- ae_waiting_time_subset %>% 
  mutate(year_quarter = str_c(year, year_quarter))

ae_waiting_time_clean <- ae_waiting_time_subset %>% 
  filter(year != "2022") %>% 
   filter(year_quarter != "2021Q4") %>% 
   select(c(1:9))

ae_waiting_time_clean <- ae_waiting_time_clean %>% 
  mutate(number_meeting_target_aggregate = coalesce(number_meeting_target_aggregate, 0)) %>% 
  mutate(attendance_greater8hrs = coalesce(attendance_greater8hrs, 0)) %>% 
  mutate(attendance_greater12hrs = coalesce(attendance_greater12hrs, 0))

write_csv(ae_waiting_time_subset, file = here::here("data/ae_waiting_time_subset.csv"))

write_csv(ae_waiting_time_clean, file = here::here("data/ae_waiting_time_clean.csv"))

```

```{r}
library(ggplot2)
```


```{r}



colnames(ae_waiting_time_clean)
  
  sum_attendances_aggregate <- ae_waiting_time_clean %>% 
  group_by(year_quarter) %>% 
  summarise_at(vars(number_of_attendances_aggregate),
  list(sum_attendances_aggregate = sum))

  sum_target_aggregate <- ae_waiting_time_clean %>% 
  group_by(year_quarter) %>% 
  summarise_at(vars(number_meeting_target_aggregate),
  list(sum_target_aggregate = sum))
  
  sum_greater_8hrs <- ae_waiting_time_clean %>% 
  group_by(year_quarter)%>% 
  summarise_at(vars(attendance_greater8hrs),
  list(sum_greater_8hrs = sum))
  
  sum_greater_12hrs <- ae_waiting_time_clean %>% 
  group_by(year_quarter)%>% 
  summarise_at(vars(attendance_greater12hrs),
  list(sum_greater_12hrs = sum))
  

  
  
 
    
  

 
  
  group_by(fall) %>% 
  summarise_at(vars(mass_g),
  list(avg_mass_g = mean))
  
  
  ae_waiting_time_clean %>% 
    mutate(year_quarter = as.factor(year_quarter)) %>% 
    geom_line(aes(x=year_quarter))
  

```

