---
title: "ae_waiting_time"
output: html_notebook
---

```{r}

library(tidyverse)
library(janitor)
library(lubridate)
library(stringr)

```

```{r}

ae_waiting_time <- read_csv(here::here("data/ae_activity_waiting_times_apr2022-data.csv")) %>% 
  clean_names()

ae_waiting_time_prior <- read_csv(here::here("data/monthly_ae_waitingtimes_A&E attendances and performance data_202201.csv")) %>% 
  clean_names()

```

__Data Cleaning__

```{r}

ae_waiting_time_prior %>% 
  left_join(ae_waiting_time_prior, location_code, by = "treatment_location", all.x = TRUE)

ae_waiting_time_prior <- ae_waiting_time_prior %>% 
  mutate(year = str_c(
    str_sub(month, start = 1, end = 4)), .before = 1) %>% 
  mutate(month = str_c(
    str_sub(month, start = 5, end = 6)
  ))


ae_waiting_time_prior <- ae_waiting_time_prior %>% 
  filter(year >= 2016)

colnames(ae_waiting_time_prior)

ae_waiting_time_subset <- ae_waiting_time_prior %>% 
  select("year", "month" , "treatment_location" , "department_type", "number_of_attendances_aggregate",  "number_meeting_target_aggregate","attendance_greater8hrs", "attendance_greater12hrs", "discharge_destination_admission_to_same" , "discharge_destination_other_specialty" ,"discharge_destination_residence", "discharge_destination_transfer" ,"discharge_destination_unknown")

ae_waiting_time_subset <- ae_waiting_time_subset %>% 
  filter( year != "2016" | month != "01") %>%
  filter( year != "2016" | month != "02") %>%
  filter( year != "2016" | month != "03") %>%
  filter( year != "2016" | month != "04") %>%
  filter( year != "2016" | month != "05") %>%
  filter( year != "2016" | month != "06")

ae_waiting_time_subset <- ae_waiting_time_subset %>% 
  mutate(year_quarter = case_when(
    str_detect(month, "01|02|03") ~ "Q1",
    str_detect(month, "04|05|06") ~ "Q2",
    str_detect(month, "07|08|09") ~ "Q3",
    str_detect(month, "10|11|12") ~ "Q4"
  ), .after = 1)
           
ae_waiting_time_subset <- ae_waiting_time_subset %>% 
  mutate(year_quarter = str_c(year, year_quarter))

ae_waiting_time_clean <- ae_waiting_time_subset %>%   
   select(c(1:9))                                     

# filter(year != "2022") %>% 
# filter(year_quarter != "2021Q4") %>% 

ae_waiting_time_clean <- ae_waiting_time_clean %>% 
  mutate(number_meeting_target_aggregate = coalesce(number_meeting_target_aggregate, 0)) %>% 
  mutate(attendance_greater8hrs = coalesce(attendance_greater8hrs, 0)) %>% 
  mutate(attendance_greater12hrs = coalesce(attendance_greater12hrs, 0))

write_csv(ae_waiting_time_subset, file = here::here("data/ae_waiting_time_subset.csv"))

write_csv(ae_waiting_time_clean, file = here::here("data/ae_waiting_time_clean.csv"))

```

```{r}
library(ggplot2)
```


```{r}

ae_waiting_time_clean <- ae_waiting_time_clean %>% 
  mutate(year_quarter = as_factor(year_quarter)) 

  
  avg_ae_waiting_time <- ae_waiting_time_clean %>% 
    group_by(year_quarter) %>% 
    summarise(mean(number_of_attendances_aggregate),
              mean(number_meeting_target_aggregate),
              mean(attendance_greater8hrs),
              mean(attendance_greater12hrs))
    

```


```{r}

ae_waiting_time_clean_long <- ae_waiting_time_clean %>% 
  rename("hrs_waiting_4" = number_meeting_target_aggregate,
         "hrs_more_waiting_8" = attendance_greater8hrs,
         "hrs_more_waiting_12" = attendance_greater12hrs) 

ae_waiting_time_clean_long_p <-ae_waiting_time_clean_long %>%
  pivot_longer(cols = c(hrs_waiting_4,hrs_more_waiting_8, hrs_more_waiting_12), names_to =  "hrs_waiting", values_to = "number_attendances") %>%
  mutate( year = as.numeric(year))

```


```{r}
location_code <- ae_waiting_time %>% 
  select(4:5) %>% 
  rename("treatment_location" = "treatment_location_code")
```

```{r}

ae_waiting_time_clean_long_p <- left_join(ae_waiting_time_clean_long_p, location_code, by = "treatment_location") %>% 
  unique() %>% 
  relocate(treatment_location_name, .after = 4) 
  

ae_waiting_time_clean_long_p <- ae_waiting_time_clean_long_p %>% 
  filter(department_type == "Emergency Department")



```

```{r}

unique(ae_waiting_time_clean_long_p$year_quarter)

```

__Plots__

```{r}

 plot_data_4hrs <- ae_waiting_time_clean_long_p %>% 
  group_by(year_quarter) %>% 
  filter(hrs_waiting == "hrs_waiting_4") %>% 
  summarise(total_attendances = sum(number_attendances)) %>% 
  mutate(time_waiting = "4hrs", .after = 1)

plot_data_8hrs <- ae_waiting_time_clean_long_p %>% 
  group_by(year_quarter) %>% 
  filter(hrs_waiting == "hrs_more_waiting_8") %>% 
  summarise(total_attendances = sum(number_attendances)) %>% 
  mutate(time_waiting = "8hrs", .after = 1)

plot_data_12hrs <- ae_waiting_time_clean_long_p %>% 
  group_by(year_quarter) %>% 
  filter(hrs_waiting == "hrs_more_waiting_12") %>% 
  summarise(total_attendances = sum(number_attendances)) %>% 
  mutate(time_waiting = "12hrs", .after = 1)

plot_data_waiting_time <- rbind(plot_data_4hrs, plot_data_8hrs, plot_data_12hrs)


#Number of People in Waiting Time Range
plot_data_waiting_time %>% 
  group_by(year_quarter) %>% 
  ggplot()+
  aes(x = year_quarter, y = total_attendances, group = time_waiting, colour = time_waiting)+
  geom_point()+
  geom_line()+
  xlab("Year(Quarter)")+ylab("Number of Attendances")+
  theme(axis.text.x = element_text(angle = 90, size = 5, vjust = 0.5, hjust=1))+
  labs(color="Time Waiting", size = 5)+
  ggtitle("Number of People in Waiting Time Range")

  
```



```{r}

#Number of A&E Attendances from 2016 to 2022
ae_waiting_time_clean_long_p %>% 
  group_by(year_quarter) %>% 
  # filter(hrs_waiting == "hrs_waiting_4") %>% 
  summarise(total_attendances = sum(number_attendances)) %>% 
  ggplot()+
  aes(x = year_quarter, y = total_attendances)+
  geom_point()+
  geom_line(group = 1)+
  xlab("Year(Quarter)")+ylab("Number of Attendances")+
  theme(axis.text.x = element_text(angle = 90, size = 5, vjust = 0.5, hjust=1))+
  labs(color="Time Waiting", size = 5)+
  ggtitle("Number of A&E Attendances from 2016 to 2022")


```


__geospatial__

```{r}

ae_waiting_time_clean_long_p %>% 
  distinct(treatment_location)

```











