---
title: "Demographic Analysis"
subtitle: rshiny group project
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(here)
library(readxl)
library(janitor)
library(ggplot2)
```


```{r}
# hosp_activity_page <- read_csv(here("data/hospital_activity_page.csv"))
# hosp_activity_by_speciality <- 
#   read_csv(here("data/Hospital Activity by Speciality.csv"))

hosp_activity_and_demographics <- 
  read_csv(here("data/Hospital Activity and Patient Demographics.csv"))
hosp_activity_and_deprivation <- 
  read_csv(here("data/Hospital Activity and Deprivation.csv"))
# 
# aAndE_waiting_times <- 
#   read_excel(here("data/monthly_ae_waitingtimes_A&E attendances and performance data_202201.xlsx"))
```


```{r}
covid_ads_HB_deprivation <- 
  read_excel(here("data/Hospitalisations due to Covid 19/Admissions By Health Board and Deprivation_20220302.xlsx"))

# covid_ads_HB_and_speciality <- 
#   read_excel(here("data/Hospitalisations due to Covid 19/Admissions By Health Board and Specialty_20220302.xlsx"))
covid_ads_HB_age_sex <- 
  read_excel(here("data/Hospitalisations due to Covid 19/Admissions By Health Board, Age and Sex_20220302.xlsx"))
covid_ads_HSCP_deprivation <- 
   read_excel(here("data/Hospitalisations due to Covid 19/Admissions By HSCP and Deprivation_20220302.xlsx"))
# covid_ads_HSCP_speciality <- 
#   read_excel(here("data/Hospitalisations due to Covid 19/Admissions By HSCP and Specialty_20220302.xlsx"))
covid_ads_HSCP_age_sex <- 
  read_excel(here("data/Hospitalisations due to Covid 19/Admissions By HSCP, Age and Sex_20220302.xlsx"))
```


Clean names
```{r}
hosp_activity_and_demographics <- 
  janitor::clean_names(hosp_activity_and_demographics)
hosp_activity_and_deprivation <- 
  janitor::clean_names(hosp_activity_and_deprivation)
covid_ads_HB_deprivation <- 
  janitor::clean_names(covid_ads_HB_deprivation)
covid_ads_HB_age_sex <- 
  janitor::clean_names(covid_ads_HB_age_sex)
covid_ads_HSCP_deprivation <- 
  janitor::clean_names(covid_ads_HSCP_deprivation)
covid_ads_HSCP_age_sex <- 
  janitor::clean_names(covid_ads_HSCP_age_sex)
```


Do they match? 
```{r}
names(hosp_activity_and_demographics)
names(hosp_activity_and_deprivation)
names(covid_ads_HB_deprivation)
names(covid_ads_HB_age_sex)
names(covid_ads_HSCP_deprivation)
names(covid_ads_HSCP_age_sex)
```

```{r}
hosp_activity_and_demographics %>% 
  distinct(age)
# 10 year increments i.e. 0-9, 10-19... 80-89, 90 years and over
# No NA values
hosp_activity_and_demographics %>% 
  mutate(age = is.na(age)) %>% 
  filter(age == TRUE)
```

```{r}
# 7 General hosp admission types for both demographics and deprivation:
# Elective Inpatients
# Emergency Inpatients,  (THIS IS THE ONLY DEFINITELY ACUTE ONE)
# Transfers
# All Day cases
# All Inpatients
# All inpatients and Day Cases
# Not Specified 
# No NAs.
hosp_activity_and_demographics %>% 
  distinct(admission_type)
hosp_activity_and_deprivation %>% 
  distinct(admission_type)

# 3 COVID ADMISSION TYPES for HB and HSCP - deprivation and age/sex: 
# All - Emergency - Planned
covid_ads_HB_deprivation %>% 
  distinct(admission_type)
covid_ads_HB_age_sex %>% 
  distinct(admission_type)
covid_ads_HSCP_deprivation %>% 
  distinct(admission_type)
covid_ads_HSCP_age_sex %>% 
  distinct(admission_type)  


# tried them all for NA and there are none
# hosp_activity_and_demographics %>% 
#   mutate(admission_type = is.na(admission_type)) %>% 
#   filter(admission_type == TRUE)
```

<br>

<hr>

## General Hospital Admissions 

### November 14th 2019 - February 22nd 2020

<br>

#### Sex 

<br>
```{r}
# 2 sex = Female, Male 
hosp_activity_and_demographics %>% 
  distinct(sex)

hosp_activity_and_demographics %>% 
  mutate(sex = is.na(sex)) %>% 
  filter(sex == TRUE)
# No NAs
```
<br> 

**Sex against time and admissions**

Filter for acute services: 

```{r}
# might want to make use of this if we're not sure about admission types
# acute_target <- c("Emergency Inpatients", "Not Specified")
# Others = Elective Inpatients, Transfers, All Day cases, All Inpatients, All 
# Inpatients and Day cases, Not Specified

general_admissions_acute <- hosp_activity_and_demographics %>% 
  filter(admission_type == "Emergency Inpatients")
general_admissions_acute
```


Now group by and create graphs over time: 

```{r}

gen_admissions_sex_per_quarter <- general_admissions_acute %>% 
  group_by(quarter, sex) %>% 
  summarise(total_admissions_per_quarter = n())
  
gen_admissions_sex_per_quarter %>% 
  ggplot()+
  aes(x = quarter, 
      y = total_admissions_per_quarter, 
      group = sex, colour = sex)+
  geom_line() + 
  labs(x = "Quarter", 
       y = "Total Admissions", 
       title = "Total Emergency Inpatient Admissions",
       subtitle = "November 2019 to February 2022", 
       colour = "Sex") +
  theme_bw()+
  theme(axis.text.x = element_text(angle=45, hjust=0.9))

```

<br>

#### Age

```{r}

hosp_activity_and_demographics %>% 
  distinct(age) # 10 year increments i.e. 0-9, 10-19... 80-89, 90 years and over
# No NA values 

hosp_activity_and_demographics %>% 
  mutate(age = is.na(age)) %>% 
  filter(age == TRUE) # no NAs
```

```{r}
gen_admissions_age_per_quarter <- general_admissions_acute %>% # remember this 
  #is only looking at Emergency Inpatients but there are 7 groups
  group_by(quarter, age) %>% 
  summarise(total_admissions_per_quarter = n())
  
# Note that it's 0-9years that are the low values and I'll make this better soon
gen_admissions_age_per_quarter %>% 
  ggplot()+
  aes(x = quarter, 
      y = total_admissions_per_quarter, 
      group = age, colour = age)+
  geom_line() + 
  labs(x = "Quarter", 
       y = "Total Admissions", 
       title = "Total Emergency Inpatient Admissions",
       subtitle = "November 2019 to February 2022", 
       colour = "Age Group") +
  theme_bw()+
  theme(axis.text.x = element_text(angle=45, hjust=0.9))

gen_admissions_age_per_quarter %>% 
  ggplot()+
  aes(x = quarter, 
      y = total_admissions_per_quarter, 
      group = age)+
  geom_col() + 
  facet_wrap(~age)+
  labs(x = "Quarter", 
       y = "Total Admissions", 
       title = "JUST MADE THIS TO SEE THE DIFFERENCE - AWARE IT'S MESSY - 
       Total Emergency Inpatient Admissions",
       subtitle = "November 2019 to February 2022") +
  theme_bw()+
  theme(axis.text.x = element_text(angle=45, hjust=0.9))
```

